name: "Quarto Render"
branding:
  icon: 'award'  
  color: 'blue'
description: "Renders a repo of documents with Quarto"
runs:
  using: "composite"
  steps: 
    - name: "Download Quarto"
      shell: bash
      run: |
        # Get the latest version via the trick found here
        # https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c

        get_latest_release() {
          curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
            grep '"tag_name":' |                                            # Get tag line
            sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
        }

        quarto_version=$(get_latest_release "quarto-dev/quarto-cli")
        quarto_file_name="quarto-$(echo ${quarto_version} | sed 's/^v//')-amd64.deb"
        quarto_url="https://github.com/quarto-dev/quarto-cli/releases/download/${quarto_version}/${quarto_file_name}"

        wget -q "${quarto_url}"

        sudo dpkg -i "${quarto_file_name}"

    - name: "Quarto render"
      shell: bash
      run: |
        quarto render --execute-debug
